routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
| $2y$10$fcCiT9H3uH6lFs.UmFmFO.IQ3IO.cfCIzlLt5z8/0kRJ4tSBI1kC2 => 123456
*/

Auth::routes();
Route::get('/','HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');
Route::view('/about', 'includes.front.about')->name('about');
Route::view('/contact', 'includes.front.contact')->name('contact');
Route::post('/logout', 'Auth\LoginController@userLogout')->name('logout');

// Password Reset Routes...
Route::get('password/reset/{token?}', 'Auth\ResetPasswordController@showResetForm')->name('password.update');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.reset');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
Route::get('password/email','Auth\ForgotPasswordController@showLinkRequestForm')->name('password.email');

# Admin Login
Route::group(['prefix' => 'admin-panel', 'namespace' => 'Auth\Admin'], function() {
	Route::get('/login', 'AdminLoginController@showAdminLoginForm')->name('admin-panel.login');
	Route::post('/login', 'AdminLoginController@adminLogin')->name('admin.submit.login');
	Route::post('/logout', 'AdminLoginController@adminLogout')->name('admin.logout');
});

# Company Login
Route::group(['prefix' => 'company-panel', 'namespace' => 'Auth\Company'], function() {
	Route::get('/login', 'CompanyLoginController@showCompanyLoginForm')->name('company-panel.login');
	Route::get('/register', 'CompanyRegisterController@showRegistrationForm')->name('company-panel.register');
	Route::post('/register', 'CompanyRegisterController@register')->name('company.register');
	Route::post('/login', 'CompanyLoginController@companyLogin')->name('company.submit.login');
	Route::post('/logout', 'CompanyLoginController@companyLogout')->name('company.logout');
});

# Admin routes
Route::group(['prefix' => 'admin-panel', 'middleware' => 'auth:admin', 'namespace' => 'Backend'], function() 
{
	Route::get('/', 'AdminController@home')->name('admin-panel');

	// admin -> jops Routes
	Route::resource('jops', 'JopController', ['except' => ['show']]);
	Route::post('ajax-change-jop-status', 'JopController@ChangeJopStatus');
	Route::post('/jops/ajax-delete-jop', 'JopController@DeleteJop');
	Route::post('/jops/all/ajax-restore-jop', 'JopController@RestoreJop');
	Route::post('/jops/all/ajax-remove-jop', 'JopController@RemoveJop');
	Route::get('/jops/all/trashed', 'JopController@Trashed')->name('jops.trashed');

	// admin -> departments Routes
	Route::resource('departments', 'DepartmentController', ['except' => ['show']]);
	Route::post('ajax-change-department-status', 'DepartmentController@ChangeDepartmentStatus');
	Route::post('/departments/ajax-delete-department', 'DepartmentController@DeleteDepartment');
	Route::post('/departments/all/ajax-restore-department', 'DepartmentController@RestoreDepartment');
	Route::post('/departments/all/ajax-remove-department', 'DepartmentController@RemoveDepartment');
	Route::get('/departments/all/trashed', 'DepartmentController@Trashed')->name('departments.trashed');

	// admin -> companies Routes
	Route::resource('companies', 'CompanyController', ['except' => ['show']]);
	Route::post('ajax-change-company-status', 'CompanyController@ChangeCompanyStatus');
	Route::post('/companies/ajax-delete-company', 'CompanyController@DeleteCompany');
	Route::post('/companies/all/ajax-restore-company', 'CompanyController@RestoreCompany');
	Route::post('/companies/all/ajax-remove-company', 'CompanyController@RemoveCompany');
	Route::get('/companies/all/trashed', 'CompanyController@Trashed')->name('companies.trashed');

	// admin -> cities Routes
	Route::resource('cities', 'CityController', ['except' => ['show']]);
	Route::post('ajax-change-city-status', 'CityController@ChangeCityStatus');
	Route::post('/cities/ajax-delete-city', 'CityController@DeleteCity');
	Route::post('/cities/all/ajax-restore-city', 'CityController@RestoreCity');
	Route::post('/cities/all/ajax-remove-city', 'CityController@RemoveCity');
	Route::get('/cities/all/trashed', 'CityController@Trashed')->name('cities.trashed');

	// admin -> courses Routes
	Route::resource('courses', 'CourseController', ['except' => ['show']]);
	Route::post('ajax-change-course-status', 'CourseController@ChangeCourseStatus');
	Route::post('/courses/ajax-delete-course', 'CourseController@DeleteCourse');
	Route::post('/courses/all/ajax-restore-course', 'CourseController@RestoreCourse');
	Route::post('/courses/all/ajax-remove-course', 'CourseController@RemoveCourse');
	Route::get('/courses/all/trashed', 'CourseController@Trashed')->name('courses.trashed');

	// admin -> users Routes
	Route::resource('users', 'UserController', ['except' => ['show']]);
	Route::post('ajax-change-user-status', 'UserController@ChangeUserStatus');
	Route::post('/users/ajax-delete-user', 'UserController@DeleteUser');
	Route::post('/users/all/ajax-restore-user', 'UserController@RestoreUser');
	Route::post('/users/all/ajax-remove-user', 'UserController@RemoveUser');
	Route::get('/users/all/trashed', 'UserController@Trashed')->name('users.trashed');

	// admin -> Admins Routes
	Route::resource('admins', 'AdminController');
	Route::get('admin/{id}/profile', 'AdminController@adminProfile')->name('admins.profile');
	Route::post('/admin/{id}/profile', 'AdminController@AdminUpdateProfile')->name('admins.updateprofile');
	Route::post('ajax-change-admin-status', 'AdminController@ChangeAdminStatus');
	Route::post('ajax-delete-admin', 'AdminController@DeleteAdmin');
	Route::post('/admins/all/ajax-restore-admin', 'AdminController@RestoreAdmin');
	Route::post('/admins/all/ajax-remove-admin', 'AdminController@RemoveAdmin');
	Route::get('/admins/all/trashed', 'AdminController@Trashed')->name('admins.trashed');

	// admin -> Settings Routes
	Route::resource('settings', 'SettingController');
	Route::post('ajax-change-setting-status', 'SettingController@ChangeSettingStatus');
	Route::post('ajax-delete-setting', 'SettingController@DeleteSetting');
	Route::post('/settings/all/ajax-restore-setting', 'SettingController@RestoreSetting');
	Route::post('/settings/all/ajax-remove-setting', 'SettingController@RemoveSetting');
	Route::get('/settings/all/trashed', 'SettingController@Trashed')->name('settings.trashed');

	// admin -> contacts Routes
	Route::resource('contacts', 'ContactController', ['except' => ['show']]);
});

# Admin routes
Route::group(['prefix' => 'company-panel', 'middleware' => 'auth:company', 'namespace' => 'Backend'], function() 
{
	Route::get('/', 'CompanyController@home')->name('company-panel');
	Route::post('/company/{id}/jobs', 'CompanyController@AddNewJob')->name('company.jops');
	Route::get('/company/{id}/appliers', 'CompanyController@GetJobApplyers')->name('company.appliers');
	Route::get('/company/{id}/profile', 'CompanyController@companyProfile')->name('company.profile');
	Route::post('/company/{id}/profile', 'CompanyController@CompanyUpdateProfile')->name('company.updateprofile');
	Route::get('/jobs', 'CompanyController@Jobs')->name('company.jobs');
	Route::get('/company/user/{id}/profile', 'CompanyController@UserProfile')->name('company.user-profile');
	Route::get('/search', 'CompanyController@Search')->name('company.search');
});

# Student Routes
Route::group(['namespace' => 'Backend', 'middleware' => 'web'], function() {
	Route::get('/user/{id}/profile', 'UserController@UserProfile')->name('users.profile');
	Route::post('/user/{id}/profile', 'UserController@UserUpdateProfile')->name('users.updateprofile');
	Route::get('/company/{id}/profile', 'UserController@CompanyProfile')->name('users.company');
	Route::post('/user/{user_id}/jop/{jop_id}', 'UserController@SetUserJob');
	Route::post('/user/{id}/profile/project', 'UserController@SetStudentProject')->name('users.updateProject');
	Route::get('/user/{id}/courses', 'UserController@courses')->name('users.courses');
	Route::post('/contact', 'UserController@SendMessage')->name('users.contact');
	Route::get('/companies', 'UserController@Companies')->name('users.companies');
	Route::get('/jobs', 'UserController@jobs')->name('users.jops');
	Route::get('/my-jobs', 'UserController@MyJobs')->name('users.my-jobs');
	Route::post('/user/{user_id}/courses', 'UserController@AddNewCourse')->name('users.add-course');
	Route::get('/search', 'UserController@Search')->name('users.search');
});

app/Models/Admin.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Hash, DB, Image, Auth;

class Admin extends Authenticatable
{
    use Notifiable, SoftDeletes;

    protected $guarded = ['id', 'password_confirmation'];

    public $guard = 'admin';

    protected $dates = ['deleted_at'];

    protected $casts = ['status' => 'boolean', 'is_super_admin' => 'boolean']; 

    protected $hidden = ['password', 'remember_token'];

    public function scopeStatus($query, $parm)
    {
        return $query->where('status', $parm);
    }

    public function scopeIsSuperAdmin($query, $parm = 0)
    {
        return $query->where('is_super_admin', $parm);
    }

    public function city()
    {
        return $this->belongsTo('App\Models\City', 'city_id', 'id');
    }

    public function scopeWithoutSuperAdmin($query, $parm)
    {
        return ($parm) ? $query->where('is_super_admin', 0) : $query->where('is_super_admin', 1);
    }

    public function getFullnameAttribute()
    {
        return ucfirst($this->first_name) . ' ' . ucfirst($this->last_name);
    }

    public function setStatusAttribute($value) //mutator for active column.
    {
        if (is_null($value)) $value = false;

        $this->attributes['status'] = (boolean) $value;
    }

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = Hash::make($value);
    }

    public static function uploadImage($img)
    {
        $filename = 'admin_' . str_random(12) . '_' . date('Y-m-d') . '.' . strtolower($img->getClientOriginalExtension());

        if (!file_exists(public_path('uploaded/admins/')))
            mkdir(public_path('uploaded/admins/'), 0777, true);

        $path = public_path('uploaded/admins/');
        
        $img = Image::make($img)->save($path . $filename);

        return $filename;
    }

    public static function createAdmin($adminData) 
    {
        if (request()->hasFile('image')) $adminData['image'] = Admin::uploadImage($adminData['image']);
        
        else $adminData = array_except($adminData, ['image']);
        
        $createdAdmin = Admin::updateOrcreate(array_except($adminData, ['_token']));

        return $createdAdmin;
    }

    public static function updateAdmin($adminData, $currentAdmin)
    {
        if (request()->hasFile('image')) $adminData['image'] = Admin::uploadImage($adminData['image']);

        else $adminData = array_except($adminData, ['image']);

        $updateAdmin = $currentAdmin->update($adminData);

        return $updateAdmin;
    }

    public static function updateAdminStatus($adminData, $currentAdmin)
    {
        $value = $adminData['value'];

        // if the value comes with checked that mean we want the reverse value of it;
        return ($value == 'checked') ? $currentAdmin->update(['status' => 0]) : $currentAdmin->update(['status' => 1]);
    }
}

app/Http/Controllers/Backend/CityController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\CreateCityRequest;
use App\Http\Requests\EditCityRequest;
use App\Models\City;
use Auth, DB, Image, File, Validator, Response, Hash;

class CityController extends Controller
{
    public function index()
    {
        $cities = City::all();
        return view('Backend.cities.index', compact('cities'));
    }

    public function home()
    {
        return view('Backend.cities.home');
    }

    public function Trashed()
    {
        $cities = City::onlyTrashed()->get();
        return view('Backend.cities.trashed', compact('cities'));
    }

    public function create()
    {
        return view('Backend.cities.create');
    }

    public function store(CreateCityRequest $request)
    {
        $cityData = $request->all();

        if(City::createCity($cityData))
        {
            if (request()->ajax()) {
                return response()->json(['requestStatus' => true, 'message' => __('Data Added Successfully')]);
            } else {
                request()->session()->flash('status','success');
                request()->session()->flash('message',__('Data Added Successfully'));
            }
        }
        else
        {
            if(request()->ajax()) {
                return response()->json(['requestStatus' => false, 'message' => __('Internal Server Error 500')]);
            } else {
                request()->session()->flash('status','danger');
                request()->session()->flash('message',__('Internal Server Error 500'));
            }

            return back()->withInputs();
        }
        return redirect()->route('cities.index');
    }

    public function ChangeCityStatus(Request $request)
    {
        // Request ajax from index;
        $cityData = $request->all();
        $currentCity = City::find($request->id);
        
        if (!$updateCityStatus = City::updateCityStatus($cityData, $currentCity))
            return response()->json(['requestStatus' => false, 'message' => trans('Server Internal Error 500')]);

        return response()->json(['requestStatus' => true, 'message' => trans('Data Updated Successfully')]);
    }

    public function edit($id)
    {
        $city = City::find($id);
        return view('Backend.cities.edit', compact('city'));
    }

    public function update(EditCityRequest $request, $id)
    {
        $cityData = $request->all();
        $currentCity = City::find($id);
        
        if (City::updateCity($cityData, $currentCity) ) {

            if (request()->ajax()) {
                return response()->json(['requestStatus' => true, 'message' => __('Data Updated Successfully')]);
            }else{
                request()->session()->flash('status','success');
                request()->session()->flash('message',__('Data Updated Successfully'));
            }
        }else{
            if (request()->ajax()) {
                return response()->json(['requestStatus' => false, 'message' => __('Server Internal Error 500')]);
            }else{
                 request()->session()->flash('status','danger');
                 request()->session()->flash('message',__('Server Internal Error 500'));
            }
        }

        return redirect()->route('cities.edit', ['id' => $currentCity->id]);
    }

    public function DeleteCity(Request $request)
    {
        $city = City::find($request->id);

        if(!$city) return response()->json(['deleteStatus' => false, 'error' => 'Sorry, City is not exists !!']);

        try
        {
            if ($city->image) File::delete('uploaded/cities/'.$city->image);
            
            $city->delete();
            
            return response()->json(['deleteStatus' => true, 'message' => 'City Deleted Successfully']);
        }
        catch (Exception $e){ return response()->json(['deleteStatus' => false,'error' => 'Server Internal Error 500']); }

        return redirect()->route('cities.index');
    }

    public function RestoreCity(Request $request)
    {
        $restore = DB::table('cities')->where('id', $request->id)->where('deleted_at', '!=', null)->update(['deleted_at' => null]);
        
        $response['requestStatus']  = ($restore) ? true : false;
        $response['message']        = ($restore) ? 'City Restored Successfully' : 'Server Internal Error 500';

        return response()->json($response);
    }

    public function RemoveCity(Request $request)
    {
        $remove = DB::table('cities')->where('id', $request->id)->where('deleted_at', '!=', null);

        if (isset($remove->image) && $remove->image != null) File::delete('/uploaded/cities/'.$remove->image);

        $remove->delete();
        
        $response['requestStatus']  = ($remove) ? true : false;

        return response()->json($response);
    }
}

resources/views/includes/backend/head.blade.php
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

<!-- Bootstrap 3.3.7 -->
<link rel="stylesheet" href="{{ asset('admin/bower_components/bootstrap/dist/css/bootstrap.min.css') }}">

<!-- Font Awesome -->
<link rel="stylesheet" href="{{ asset('admin/bower_components/font-awesome/css/font-awesome.min.css') }}">

<!-- Ionicons -->
<link rel="stylesheet" href="{{ asset('admin/bower_components/Ionicons/css/ionicons.min.css') }}">

<!-- Theme style -->
<link rel="stylesheet" href="{{ asset('admin/dist/css/AdminLTE.min.css') }}">

<!-- AdminLTE Skins. Choose a skin from the css/skins
     folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="{{ asset('admin/dist/css/skins/_all-skins.min.css') }}">

<!-- Date Picker -->
<link rel="stylesheet" href="{{ asset('admin/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}">

<!-- Daterange picker -->
<link rel="stylesheet" href="{{ asset('admin/bower_components/bootstrap-daterangepicker/daterangepicker.css') }}">

<!-- bootstrap wysihtml5 - text editor -->
<link rel="stylesheet" href="{{ asset('admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }}">

<style>
	.switch {
	  position: relative;
	  display: inline-block;
	  width: 60px;
	  height: 34px;
	}

	.switch input { 
	  opacity: 0;
	  width: 0;
	  height: 0;
	}

	.slider {
	  position: absolute;
	  cursor: pointer;
	  top: 0;
	  left: 0;
	  right: 0;
	  bottom: 0;
	  background-color: #ccc;
	  -webkit-transition: .4s;
	  transition: .4s;
	}

	.slider:before {
	  position: absolute;
	  content: "";
	  height: 26px;
	  width: 26px;
	  left: 4px;
	  bottom: 4px;
	  background-color: white;
	  -webkit-transition: .4s;
	  transition: .4s;
	}

	input:checked + .slider {
	  background-color: #2196F3;
	}

	input:focus + .slider {
	  box-shadow: 0 0 1px #2196F3;
	}

	input:checked + .slider:before {
	  -webkit-transform: translateX(26px);
	  -ms-transform: translateX(26px);
	  transform: translateX(26px);
	}

	/* Rounded sliders */
	.slider.round {
	  border-radius: 34px;
	}

	.slider.round:before {
	  border-radius: 50%;
	}
</style>

resources/views/includes/backend/header.blade.php
<header class="main-header">
    <a href="{{ route('admin-panel') }}" class="logo">
        <span class="logo-mini"><b>C</b>TJ</span>
        <span class="logo-lg"><b>CTJ</b> Finder</span>
    </a>

    <nav class="navbar navbar-static-top">
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button"><span class="sr-only">Toggle navigation</span></a>
        
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown messages-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope-o"></i>
                        <span class="label label-success">{{ contact()->count() }}</span>
                    </a>

                    <ul class="dropdown-menu">
                        <li class="header">You have {{ contact()->count() }} messages</li>
                        <li>
                            <ul class="menu">
                                @forelse(contact()->get() as $message)
                                @php
                                    $user = user()->where('email', $message->email)->get();
                                    $image = $user->count() > 0 ? $user->image : null;
                                @endphp
                                <li onclick="setMessageToBeSeen({{ $message->id }});">
                                    <a href="{{ route('contacts.index') }}">
                                        <div class="pull-left">
                                            <img src="{{ getImage('user', $image) }}" class="img-circle" alt="User Image">
                                        </div>
                                        <h4>{{ $message->subject }}<small><i class="fa fa-clock-o"></i> {{ $message->created_at->diffForHumans() }}</small></h4>
                                        <p>{{ limit($message->message, 20) }}</p>
                                    </a>
                                </li>
                                @empty
                                No Messages
                                @endforelse
                            </ul>
                        </li>
                        <li class="footer"><a href="{{ route('contacts.index') }}">See All Messages</a></li>
                    </ul>
                </li>

                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{ getImage('admin', $auth->image) }}" class="user-image" alt="@isset($auth) {{ $auth->fullname }} @endisset">
                        <span class="hidden-xs">{{ ucwords($auth->fullname) }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="{{ getImage('admin', $auth->image) }}" class="img-circle" alt="User Image">
                            <p>
                                @isset($auth) {{ ucwords($auth->fullname) }} @else UNKNOWN @endisset - is a Admininstrator
                                <small> Member since @isset($auth) {{ $auth->created_at->format('M. Y') }} @endisset </small>
                            </p>
                        </li>

                        <!-- Menu Body -->
                        <li class="user-body"></li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{{ route('admins.profile', ['id' => $auth->id]) }}" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">

                                <a class="btn btn-default btn-flat" href="{{ route('admin.logout') }}"
                                   onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                    {{ __('Sign out') }}
                                </a>

                                    @csrf
                                </form>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/includes/backend/inputs.blade.php
@if($type == 'password_confirmation')

	<div class="col-xs-{{ $col }} {{ $errors->first($name , 'has-error') }}">
		<div class="form-valid floating">
			<label for="password_confirmation">Confirm</label>
			{!! Form::password('password_confirmation', ['class'=>'form-control form-data','id' => 'password_confirmation']) !!}
		</div>
		{!! $errors->first('password' , '<div class="help-block text-right animated fadeInDown val-error">:message</div>') !!}
	</div>

@elseif($type == 'password')

	<div class="col-xs-{{ $col }} {{ $errors->first($name , 'has-error') }}">
		<div class="form-valid floating">
			<label for="{{ $name }}">{{ ucwords($name) }}</label>
			{!! Form::password($name, ['class'=>'form-control form-data','id' => $name]) !!}
		</div>
		{!! $errors->first('password' , '<div class="help-block text-right animated fadeInDown val-error">:message</div>') !!}
	</div>

@elseif($type == 'select')

	<div class="col-xs-{{ $col }} {{ $errors->first($name , 'has-error') }}">
		<div class="form-valid floating">
			<label for="{{ $name }}">{{ ucwords(explode('_', $name)[0]) }}</label>
			{!! Form::select($name, $list, 'Select a value', ['class'=>'form-control form-data','id' => $name]) !!}
		</div>
		{!! $errors->first($name , '<div class="help-block text-right animated fadeInDown val-error">:message</div>') !!}
	</div>

@else

	<div class="col-xs-{{ $col }} {{ $errors->first($name , 'has-error') }}">
		<div class="form-valid floating">
			<label for="{{ $name }}">{{ ucwords(str_replace('_', ' ',$name)) }}</label>
			{!! Form::{$type}($name, null, ['class'=>$style,'id' => $name, 'autocomplete' => 'off']) !!}
			{!! $errors->first($name , '<div class="help-block text-right animated fadeInDown val-error">:message</div>') !!}
		</div>
	</div>

@endif

resources/views/includes/backend/sidebar.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ getImage('admin', $auth->image) }}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{ ucwords($auth->name) }}</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        <!-- /.search form -->
      
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">

            @if(Auth::user()->guard == 'admin')

                <li class="header">ADMIN MAIN NAVIGATION</li>

                @foreach(models() as $model)
                    @if($model[0] != 'contact')
                    <li class="{{ Request::is('admin-panel/'.str()->plural($model[0]).'/*') ? ' active ' : '' }} {{ Request::is('admin-panel/'.str()->plural($model[0])) ? 'active' : '' }} treeview">
                        <a href="#">
                            <i class="ion {{ $model[1] }}"></i>
                            <span>{{ ucfirst(str()->plural($model[0])) }}</span>
                            <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                        </a>
                        <ul class="treeview-menu">
                            <li class="{{ Request::is('admin-panel/'.str()->plural($model[0])) ? 'active' : '' }}">
                                <a href="{{ route(str()->plural($model[0]).'.index') }}">
                                    <i class="fa fa-circle-o"></i>
                                    <span class="pull-right-container">
                                        <small class="label pull-right bg-blue">{{ getModelCount($model[0]) }}</small>
                                    </span> All
                                </a>
                            </li>
                            <li class="{{ Request::is('admin-panel/'.str()->plural($model[0]).'/create') ? 'active' : '' }}">
                                <a href="{{ route(str()->plural($model[0]).'.create') }}"><i class="fa fa-circle-o"></i> Add</a>
                            </li>
                            <li class="{{ Request::is('admin-panel/'.str()->plural($model[0]).'/all/trashed') ? 'active' : '' }}">
                                <a href="{{ route(str()->plural($model[0]).'.trashed') }}">
                                    <i class="fa fa-circle-o"></i> 
                                    <span class="pull-right-container">
                                        <small class="label pull-right bg-red">{{ getModelCount($model[0], true) }}</small>
                                    </span> Trashed
                                </a>
                            </li>
                        </ul>
                    </li>
                    @endif
                @endforeach

                <li>
                    <a href="{{ route('contacts.index') }}">
                        <i class="fa fa-envelope"></i> <span>Mailbox</span>
                        <span class="pull-right-container">
                            <small class="label pull-right bg-green">{{ contact()->count() }}</small>
                        </span>
                    </a>
                </li>
            @endif
        </ul>
    </section>
</aside>