routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
| $2y$10$fcCiT9H3uH6lFs.UmFmFO.IQ3IO.cfCIzlLt5z8/0kRJ4tSBI1kC2 => 123456
*/

Auth::routes();
Route::get('/','HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');
Route::view('/about', 'includes.front.about')->name('about');
Route::view('/contact', 'includes.front.contact')->name('contact');
Route::post('/logout', 'Auth\LoginController@userLogout')->name('logout');

// Password Reset Routes...
Route::get('password/reset/{token?}', 'Auth\ResetPasswordController@showResetForm')->name('password.update');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.reset');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
Route::get('password/email','Auth\ForgotPasswordController@showLinkRequestForm')->name('password.email');

# Admin Login
Route::group(['prefix' => 'admin-panel', 'namespace' => 'Auth\Admin'], function() {
	Route::get('/login', 'AdminLoginController@showAdminLoginForm')->name('admin-panel.login');
	Route::post('/login', 'AdminLoginController@adminLogin')->name('admin.submit.login');
	Route::post('/logout', 'AdminLoginController@adminLogout')->name('admin.logout');
});

# Company Login
Route::group(['prefix' => 'company-panel', 'namespace' => 'Auth\Company'], function() {
	Route::get('/login', 'CompanyLoginController@showCompanyLoginForm')->name('company-panel.login');
	Route::get('/register', 'CompanyRegisterController@showRegistrationForm')->name('company-panel.register');
	Route::post('/register', 'CompanyRegisterController@register')->name('company.register');
	Route::post('/login', 'CompanyLoginController@companyLogin')->name('company.submit.login');
	Route::post('/logout', 'CompanyLoginController@companyLogout')->name('company.logout');
});

# Admin routes
Route::group(['prefix' => 'admin-panel', 'middleware' => 'auth:admin', 'namespace' => 'Backend'], function() 
{
	Route::get('/', 'AdminController@home')->name('admin-panel');

	// admin -> jops Routes
	Route::resource('jops', 'JopController', ['except' => ['show']]);
	Route::post('ajax-change-jop-status', 'JopController@ChangeJopStatus');
	Route::post('/jops/ajax-delete-jop', 'JopController@DeleteJop');
	Route::post('/jops/all/ajax-restore-jop', 'JopController@RestoreJop');
	Route::post('/jops/all/ajax-remove-jop', 'JopController@RemoveJop');
	Route::get('/jops/all/trashed', 'JopController@Trashed')->name('jops.trashed');

	// admin -> departments Routes
	Route::resource('departments', 'DepartmentController', ['except' => ['show']]);
	Route::post('ajax-change-department-status', 'DepartmentController@ChangeDepartmentStatus');
	Route::post('/departments/ajax-delete-department', 'DepartmentController@DeleteDepartment');
	Route::post('/departments/all/ajax-restore-department', 'DepartmentController@RestoreDepartment');
	Route::post('/departments/all/ajax-remove-department', 'DepartmentController@RemoveDepartment');
	Route::get('/departments/all/trashed', 'DepartmentController@Trashed')->name('departments.trashed');

	// admin -> companies Routes
	Route::resource('companies', 'CompanyController', ['except' => ['show']]);
	Route::post('ajax-change-company-status', 'CompanyController@ChangeCompanyStatus');
	Route::post('/companies/ajax-delete-company', 'CompanyController@DeleteCompany');
	Route::post('/companies/all/ajax-restore-company', 'CompanyController@RestoreCompany');
	Route::post('/companies/all/ajax-remove-company', 'CompanyController@RemoveCompany');
	Route::get('/companies/all/trashed', 'CompanyController@Trashed')->name('companies.trashed');

	// admin -> cities Routes
	Route::resource('cities', 'CityController', ['except' => ['show']]);
	Route::post('ajax-change-city-status', 'CityController@ChangeCityStatus');
	Route::post('/cities/ajax-delete-city', 'CityController@DeleteCity');
	Route::post('/cities/all/ajax-restore-city', 'CityController@RestoreCity');
	Route::post('/cities/all/ajax-remove-city', 'CityController@RemoveCity');
	Route::get('/cities/all/trashed', 'CityController@Trashed')->name('cities.trashed');

	// admin -> courses Routes
	Route::resource('courses', 'CourseController', ['except' => ['show']]);
	Route::post('ajax-change-course-status', 'CourseController@ChangeCourseStatus');
	Route::post('/courses/ajax-delete-course', 'CourseController@DeleteCourse');
	Route::post('/courses/all/ajax-restore-course', 'CourseController@RestoreCourse');
	Route::post('/courses/all/ajax-remove-course', 'CourseController@RemoveCourse');
	Route::get('/courses/all/trashed', 'CourseController@Trashed')->name('courses.trashed');

	// admin -> users Routes
	Route::resource('users', 'UserController', ['except' => ['show']]);
	Route::post('ajax-change-user-status', 'UserController@ChangeUserStatus');
	Route::post('/users/ajax-delete-user', 'UserController@DeleteUser');
	Route::post('/users/all/ajax-restore-user', 'UserController@RestoreUser');
	Route::post('/users/all/ajax-remove-user', 'UserController@RemoveUser');
	Route::get('/users/all/trashed', 'UserController@Trashed')->name('users.trashed');

	// admin -> Admins Routes
	Route::resource('admins', 'AdminController');
	Route::get('admin/{id}/profile', 'AdminController@adminProfile')->name('admins.profile');
	Route::post('/admin/{id}/profile', 'AdminController@AdminUpdateProfile')->name('admins.updateprofile');
	Route::post('ajax-change-admin-status', 'AdminController@ChangeAdminStatus');
	Route::post('ajax-delete-admin', 'AdminController@DeleteAdmin');
	Route::post('/admins/all/ajax-restore-admin', 'AdminController@RestoreAdmin');
	Route::post('/admins/all/ajax-remove-admin', 'AdminController@RemoveAdmin');
	Route::get('/admins/all/trashed', 'AdminController@Trashed')->name('admins.trashed');

	// admin -> Settings Routes
	Route::resource('settings', 'SettingController');
	Route::post('ajax-change-setting-status', 'SettingController@ChangeSettingStatus');
	Route::post('ajax-delete-setting', 'SettingController@DeleteSetting');
	Route::post('/settings/all/ajax-restore-setting', 'SettingController@RestoreSetting');
	Route::post('/settings/all/ajax-remove-setting', 'SettingController@RemoveSetting');
	Route::get('/settings/all/trashed', 'SettingController@Trashed')->name('settings.trashed');

	// admin -> contacts Routes
	Route::resource('contacts', 'ContactController', ['except' => ['show']]);
});

# Admin routes
Route::group(['prefix' => 'company-panel', 'middleware' => 'auth:company', 'namespace' => 'Backend'], function() 
{
	Route::get('/', 'CompanyController@home')->name('company-panel');
	Route::post('/company/{id}/jobs', 'CompanyController@AddNewJob')->name('company.jops');
	Route::get('/company/{id}/appliers', 'CompanyController@GetJobApplyers')->name('company.appliers');
	Route::get('/company/{id}/profile', 'CompanyController@companyProfile')->name('company.profile');
	Route::post('/company/{id}/profile', 'CompanyController@CompanyUpdateProfile')->name('company.updateprofile');
	Route::get('/jobs', 'CompanyController@Jobs')->name('company.jobs');
	Route::get('/company/user/{id}/profile', 'CompanyController@UserProfile')->name('company.user-profile');
	Route::get('/search', 'CompanyController@Search')->name('company.search');
});

# Student Routes
Route::group(['namespace' => 'Backend', 'middleware' => 'web'], function() {
	Route::get('/user/{id}/profile', 'UserController@UserProfile')->name('users.profile');
	Route::post('/user/{id}/profile', 'UserController@UserUpdateProfile')->name('users.updateprofile');
	Route::get('/company/{id}/profile', 'UserController@CompanyProfile')->name('users.company');
	Route::post('/user/{user_id}/jop/{jop_id}', 'UserController@SetUserJob');
	Route::post('/user/{id}/profile/project', 'UserController@SetStudentProject')->name('users.updateProject');
	Route::get('/user/{id}/courses', 'UserController@courses')->name('users.courses');
	Route::post('/contact', 'UserController@SendMessage')->name('users.contact');
	Route::get('/companies', 'UserController@Companies')->name('users.companies');
	Route::get('/jobs', 'UserController@jobs')->name('users.jops');
	Route::get('/my-jobs', 'UserController@MyJobs')->name('users.my-jobs');
	Route::post('/user/{user_id}/courses', 'UserController@AddNewCourse')->name('users.add-course');
	Route::get('/search', 'UserController@Search')->name('users.search');
});

app/Models/Admin.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Hash, DB, Image, Auth;

class Admin extends Authenticatable
{
    use Notifiable, SoftDeletes;

    protected $guarded = ['id', 'password_confirmation'];

    public $guard = 'admin';

    protected $dates = ['deleted_at'];

    protected $casts = ['status' => 'boolean', 'is_super_admin' => 'boolean']; 

    protected $hidden = ['password', 'remember_token'];

    public function scopeStatus($query, $parm)
    {
        return $query->where('status', $parm);
    }

    public function scopeIsSuperAdmin($query, $parm = 0)
    {
        return $query->where('is_super_admin', $parm);
    }

    public function city()
    {
        return $this->belongsTo('App\Models\City', 'city_id', 'id');
    }

    public function scopeWithoutSuperAdmin($query, $parm)
    {
        return ($parm) ? $query->where('is_super_admin', 0) : $query->where('is_super_admin', 1);
    }

    public function getFullnameAttribute()
    {
        return ucfirst($this->first_name) . ' ' . ucfirst($this->last_name);
    }

    public function setStatusAttribute($value) //mutator for active column.
    {
        if (is_null($value)) $value = false;

        $this->attributes['status'] = (boolean) $value;
    }

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = Hash::make($value);
    }

    public static function uploadImage($img)
    {
        $filename = 'admin_' . str_random(12) . '_' . date('Y-m-d') . '.' . strtolower($img->getClientOriginalExtension());

        if (!file_exists(public_path('uploaded/admins/')))
            mkdir(public_path('uploaded/admins/'), 0777, true);

        $path = public_path('uploaded/admins/');
        
        $img = Image::make($img)->save($path . $filename);

        return $filename;
    }

    public static function createAdmin($adminData) 
    {
        if (request()->hasFile('image')) $adminData['image'] = Admin::uploadImage($adminData['image']);
        
        else $adminData = array_except($adminData, ['image']);
        
        $createdAdmin = Admin::updateOrcreate(array_except($adminData, ['_token']));

        return $createdAdmin;
    }

    public static function updateAdmin($adminData, $currentAdmin)
    {
        if (request()->hasFile('image')) $adminData['image'] = Admin::uploadImage($adminData['image']);

        else $adminData = array_except($adminData, ['image']);

        $updateAdmin = $currentAdmin->update($adminData);

        return $updateAdmin;
    }

    public static function updateAdminStatus($adminData, $currentAdmin)
    {
        $value = $adminData['value'];

        // if the value comes with checked that mean we want the reverse value of it;
        return ($value == 'checked') ? $currentAdmin->update(['status' => 0]) : $currentAdmin->update(['status' => 1]);
    }
}

app/Http/Controllers/Backend/CityController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\CreateCityRequest;
use App\Http\Requests\EditCityRequest;
use App\Models\City;
use Auth, DB, Image, File, Validator, Response, Hash;

class CityController extends Controller
{
    public function index()
    {
        $cities = City::all();
        return view('Backend.cities.index', compact('cities'));
    }

    public function home()
    {
        return view('Backend.cities.home');
    }

    public function Trashed()
    {
        $cities = City::onlyTrashed()->get();
        return view('Backend.cities.trashed', compact('cities'));
    }

    public function create()
    {
        return view('Backend.cities.create');
    }

    public function store(CreateCityRequest $request)
    {
        $cityData = $request->all();

        if(City::createCity($cityData))
        {
            if (request()->ajax()) {
                return response()->json(['requestStatus' => true, 'message' => __('Data Added Successfully')]);
            } else {
                request()->session()->flash('status','success');
                request()->session()->flash('message',__('Data Added Successfully'));
            }
        }
        else
        {
            if(request()->ajax()) {
                return response()->json(['requestStatus' => false, 'message' => __('Internal Server Error 500')]);
            } else {
                request()->session()->flash('status','danger');
                request()->session()->flash('message',__('Internal Server Error 500'));
            }

            return back()->withInputs();
        }
        return redirect()->route('cities.index');
    }

    public function ChangeCityStatus(Request $request)
    {
        // Request ajax from index;
        $cityData = $request->all();
        $currentCity = City::find($request->id);
        
        if (!$updateCityStatus = City::updateCityStatus($cityData, $currentCity))
            return response()->json(['requestStatus' => false, 'message' => trans('Server Internal Error 500')]);

        return response()->json(['requestStatus' => true, 'message' => trans('Data Updated Successfully')]);
    }

    public function edit($id)
    {
        $city = City::find($id);
        return view('Backend.cities.edit', compact('city'));
    }

    public function update(EditCityRequest $request, $id)
    {
        $cityData = $request->all();
        $currentCity = City::find($id);
        
        if (City::updateCity($cityData, $currentCity) ) {

            if (request()->ajax()) {
                return response()->json(['requestStatus' => true, 'message' => __('Data Updated Successfully')]);
            }else{
                request()->session()->flash('status','success');
                request()->session()->flash('message',__('Data Updated Successfully'));
            }
        }else{
            if (request()->ajax()) {
                return response()->json(['requestStatus' => false, 'message' => __('Server Internal Error 500')]);
            }else{
                 request()->session()->flash('status','danger');
                 request()->session()->flash('message',__('Server Internal Error 500'));
            }
        }

        return redirect()->route('cities.edit', ['id' => $currentCity->id]);
    }

    public function DeleteCity(Request $request)
    {
        $city = City::find($request->id);

        if(!$city) return response()->json(['deleteStatus' => false, 'error' => 'Sorry, City is not exists !!']);

        try
        {
            if ($city->image) File::delete('uploaded/cities/'.$city->image);
            
            $city->delete();
            
            return response()->json(['deleteStatus' => true, 'message' => 'City Deleted Successfully']);
        }
        catch (Exception $e){ return response()->json(['deleteStatus' => false,'error' => 'Server Internal Error 500']); }

        return redirect()->route('cities.index');
    }

    public function RestoreCity(Request $request)
    {
        $restore = DB::table('cities')->where('id', $request->id)->where('deleted_at', '!=', null)->update(['deleted_at' => null]);
        
        $response['requestStatus']  = ($restore) ? true : false;
        $response['message']        = ($restore) ? 'City Restored Successfully' : 'Server Internal Error 500';

        return response()->json($response);
    }

    public function RemoveCity(Request $request)
    {
        $remove = DB::table('cities')->where('id', $request->id)->where('deleted_at', '!=', null);

        if (isset($remove->image) && $remove->image != null) File::delete('/uploaded/cities/'.$remove->image);

        $remove->delete();
        
        $response['requestStatus']  = ($remove) ? true : false;

        return response()->json($response);
    }
}

resources/views/Backend/Settings/create.blade.php
@include('Backend.inc.create', ['model' => ['setting', getModelWithIcon('setting')[0], null]])

resources/views/Backend/Settings/edit.blade.php
@include('Backend.inc.edit', ['model' => ['setting', getModelWithIcon('setting')[0], null], 'editor' => $setting])

resources/views/Backend/Settings/form.blade.php
<div class="form-group">
	@include('includes.backend.inputs', ['errors' => $errors, 'type' => 'text', 'name' => 'key', 'style' => 'form-control form-data','col'=>'6'])
	@include('includes.backend.inputs', ['errors' => $errors, 'type' => 'text', 'name' => 'value', 'style' => 'form-control form-data','col'=>'6'])
</div>

resources/views/Backend/Settings/index.blade.php
@extends('backend.layouts.app')

@section('title', 'Settings')

@section('styles')
	<link rel="stylesheet" href="{{ asset('admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@stop

@section('content')
    
    <section class="content-header">
        <h1>Dashboard<small>Control panel</small></h1>
        <ol class="breadcrumb">
            <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Settings</li>
        </ol>
    </section>

    <section class="content">
    	<div class="row">
    		<div class="col-xs-12">
    			<div class="box">
    				<div class="box-header">
    					<h3 class="box-title">Data Table With Full Features</h3>
    				</div>
    				<!-- /.box-header -->
    				<div class="box-body">
    					<table id="settings" class="table table-bordered table-striped text-center">
    						<thead>
    							<tr>
    								<th>#</th>
    								<th>Admin</th>
				                  	<th>key</th>
				                  	<th>value</th>
				                  	<th>Status</th>
				                  	<th>Actions</th>
				                </tr>
	                		</thead>
	                		<tbody data-count={{ $settings->count() }}>
			                	@foreach($settings as $key => $setting)
					                <tr id="setting-row-{{ $setting->id }}">

					                	<td>{{ (int)$key + 1 }}</td>
					                	<td>{{ ucwords($setting->admin->fullname) }}</td>
					                	<td>{{ ucwords($setting->key) }}</td>
					                	<td>{{ $setting->value }}</td>

					                	<td>
					                		@if($setting->status == 1)
					                			<label class="switch" id="checkbox-id-{{ $setting->id }}">
					                				<input type="checkbox" class="form-control" id="#active-id-{{ $setting->id }}" onclick="isChecked('checked', '{{ $setting->id }}');" value="1" checked><span class="slider round"></span>
					                			</label>
					                		@else
					                			<label class="switch">
					                				<input type="checkbox" class="form-control" id="#active-id-{{ $setting->id }}" onclick="isChecked('null', '{{ $setting->id }}');" value="0"><span class="slider round"></span>
					                			</label>
					                		@endif
					                	</td>
					                	
					                	<td>
					                		<ul class="list-unstyled list-inline">
					                			<li>
					                				<a href="{{ route('settings.create') }}" data-toggle='tooltip' title="Add" class="btn btn-primary btn-sm">
					                					<i class="fa fa-plus"></i>
					                				</a>
					                			</li>
					                			<li>
					                				<a href="{{ route('settings.edit', ['id' => $setting->id]) }}" data-toggle='tooltip' title="Edit" class="btn btn-success btn-sm">
					                					<i class="fa fa-edit"></i>
					                				</a>
					                			</li>
					                			<li>
					                				<a 
					                					href='{{ url('/settings/'.$setting->id) }}' 
					                					
					                					class='btn btn-sm btn-danger delete-action' 
					                					
					                					type='button'

					                					data-id="{{ $setting->id }}" 
					                					
					                					data-toggle='tooltip' 
														
														title='Delete'><i class='fa fa-times'></i>
													</a>
					                			</li>
					                		</ul>
					                	</td>
					                </tr>
			                	@endforeach
	                		</tbody>
	                		<tfoot>
	                			<tr>
    								<th>#</th>
    								<th>Admin</th>
				                  	<th>key</th>
				                  	<th>value</th>
				                  	<th>Status</th>
				                  	<th>Actions</th>
	                			</tr>
	                		</tfoot>
	              		</table>
	            	</div>
	            	<!-- /.box-body -->
	          	</div>
	          	<!-- /.box -->
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
@stop

@section('scripts')
	<script src="{{ asset('admin/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
	<script src="{{ asset('admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
	<script>
	  	
	  	function isChecked(value, id)
		{
	        $.ajax({
	            type: 'POST',
	            url: 'ajax-change-setting-status',
	            data: { id: id, value: value },
	            success: function(response) 
	            {
					var dialog = bootbox.dialog({
					    message: '<p class="text-center">'+response.message+'</p>',
					    closeButton: false
					});
	                setTimeout(function(){ dialog.modal('hide'); }, 1000);
	            },
	            error: function(x) { crud_handle_server_errors(x); },
	            complete:function(){ window.location.reload(); }
	        });

		}

		$('.delete-action').on('click', function(e)
		{
			var id = $(this).data('id');
			var tbody = $('table#settings tbody');
			var count = tbody.data('count');

			e.preventDefault();
	        
	        bootbox.confirm({
	            title: 'Confirmation Message',
	            size: "small",
	            message: 'Are you sure you want to remove this setting',
	            buttons: {
	                cancel: { label: '<i class="fa fa-times"></i> Cancel' },
	                confirm: {
	                    label: '<i class="fa fa-check"></i> Confirm',
	                    className: "btn-danger"
	                }
	            },
	            callback: function(result) 
	            {
	                if (result) 
	                {
        				var tbody = $('table#settings tbody');
						var count = tbody.data('count');
						
						$.ajax({
							type: 'POST',
							url: 'ajax-delete-setting',
							data: {id: id},
							success: function(response){ 
								$('#setting-row-'+id).fadeOut(); count = count - 1;tbody.attr('data-count', count);
							},
							error: function(x) { crud_handle_server_errors(x); },
							complete: function() { 
								// if(count == 1) tbody.append(`<tr><td colspan="5"><strong>No data available in table</strong></td></tr>`);	
							}
						});
	                }
	            }
	        });
		});

		$(function () {
			$('#settings').DataTable({
	      		'paging'      : true,
	      		'lengthChange': true,
	      		'searching'   : true,
			    'ordering'    : true,
			    'info'        : true,
			    'autoWidth'   : true
	    	})
	  	});

	</script>
@stop

resources/views/Backend/Settings/trashed.blade.php
@extends('backend.layouts.app')

@section('title', 'Deleted Settings')

@section('styles')
	<link rel="stylesheet" href="{{ asset('admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@stop

@section('content')
    
    <section class="content-header">
        <h1>Dashboard<small>Control panel</small></h1>
        <ol class="breadcrumb">
            <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Trashed</li>
        </ol>
    </section>

    <section class="content">
    	<div class="row">
    		<div class="col-xs-12">
    			<div class="box">
    				<div class="box-header">
    					<h3 class="box-title">Data Table With Full Features</h3>
    				</div>
    				<!-- /.box-header -->
    				<div class="box-body">
    					<table id="settings" class="table table-bordered table-striped text-center">
    						
    						<thead>
    							<tr>
    								<th>#</th>
    								<th>Admin</th>
				                  	<th>key</th>
				                  	<th>value</th>
				                  	<th>Actions</th>
				                </tr>
	                		</thead>
	                		
	                		<tbody data-count={{ $settings->count() }}>
			                	@foreach($settings as $key => $setting)
				                <tr id="setting-row-{{ $setting->id }}">
				                	
				                	<td>{{ (int)$key+1 }}</td>
				                	<td>{{ ucwords($setting->admin->fullname) }}</td>
				                	<td>{{ ucwords($setting->key) }}</td>
				                	<td>{{ $setting->value }}</td>
				                	
				                	<td>
				                		<ul class="list-unstyled list-inline">
				                			<li>
				                				<a 
				                					href="{{ url('/settings/'.$setting->id) }}" 

				                					data-toggle='tooltip' title="Restore"

				                					data-id="{{ $setting->id }}" 

				                					class="btn btn-primary btn-sm restore-action">
				                					
				                					<i class="fa fa-repeat"></i>
				                				</a>
				                			</li>

				                			<li>
				                				<a 
				                					href='{{ url('/settings/'.$setting->id) }}' 
				                					
				                					class='btn btn-sm btn-danger delete-action' 
				                					
				                					type='button' data-id="{{ $setting->id }}"

				                					data-toggle='tooltip' title='Delete'>

				                					<i class='fa fa-times'></i>
												</a>
				                			</li>
				                		</ul>
				                	</td>
				                </tr>
			                	@endforeach
	                		</tbody>
	                		
	                		<tfoot>
	                			<tr>
    								<th>#</th>
    								<th>Admin</th>
				                  	<th>key</th>
				                  	<th>value</th>
				                  	<th>Actions</th>
	                			</tr>
	                		</tfoot>
	              		
	              		</table>
	            	</div>
	            	<!-- /.box-body -->
	          	</div>
            </div>
          </div>
        </div>
      </div>
    </section>

@stop

@section('scripts')
	<script src="{{ asset('admin/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
	<script src="{{ asset('admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
	<script>

		$('.delete-action').on('click', function(e)
		{
			var id = $(this).data('id');
			e.preventDefault();
	        
	        bootbox.confirm({
	            title: 'Confirmation Message',
	            size: "small",
	            message: 'Are you sure you want to remove this setting',
	            buttons: {
	                cancel: {
	                    label: '<i class="fa fa-times"></i> Cancel'
	                },
	                confirm: {
	                    label: '<i class="fa fa-check"></i> Confirm',
	                    className: "btn-danger"
	                }
	            },
	            callback: function(result) 
	            {
	                if (result) 
	                {
						$.ajax({
							type: 'POST',
							url: '/admin-panel/settings/all/ajax-remove-setting',
							data: {id: id},
							success: function(response){ $('#setting-row-'+id).fadeOut(); },
							error: function(x) { crud_handle_server_errors(x); },
							complete: function() {
								// var tbody = $('table#settings tbody');
								// var count = tbody.data('count');
								// if(count == 1) tbody.append(`<tr><td colspan="5"><strong>No Trashed</strong></td></tr>`);
							}
						});
	                }
	            }
	        });
		});

		$('.restore-action').on('click', function(e)
		{
			var id = $(this).data('id');
			e.preventDefault();
	        
	        bootbox.confirm({
	            title: 'Confirmation Message',
	            size: "small",
	            message: 'Are you sure you want to restore this setting',
	            buttons: {
	                cancel: {
	                    label: '<i class="fa fa-times"></i> Cancel'
	                },
	                confirm: {
	                    label: '<i class="fa fa-check"></i> Restore',
	                    className: "btn-primary"
	                }
	            },
	            callback: function(result) 
	            {
	                if (result) 
	                {
						$.ajax({
							type: 'POST',
							url: '/admin-panel/settings/all/ajax-restore-setting',
							data: {id: id},
							success: function(response){ $('#setting-row-'+id).fadeOut(); },
							error: function(x) { crud_handle_server_errors(x); },
							complete: function() { 
								// var tbody = $('table#settings tbody');
								// var count = tbody.data('count');
								// if(count == 1) tbody.append(`<tr><td colspan="5"><strong>No Trashed</strong></td></tr>`);	
							}
						});
	                }
	            }
	        });
		});

		$(function () {
			$('#settings').DataTable({
	      		'paging'      : true,
	      		'lengthChange': true,
	      		'searching'   : true,
			    'ordering'    : true,
			    'info'        : true,
			    'autoWidth'   : true
	    	})
	  	});

	</script>
@stop